// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJbRQuKh5QcpZ-h4yAdbtaVnk69lMCiGM',
    appId: '1:453272669944:web:3d33e8407f78a25cc0b50d',
    messagingSenderId: '453272669944',
    projectId: 'schederated',
    authDomain: 'schederated.firebaseapp.com',
    storageBucket: 'schederated.appspot.com',
    measurementId: 'G-8GDF4BJFTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDt-3hajB5vKghgmpRBkywD-UFsQzUvQ',
    appId: '1:453272669944:android:8b363e1e5f185dc8c0b50d',
    messagingSenderId: '453272669944',
    projectId: 'schederated',
    storageBucket: 'schederated.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCky9F4k-1SDV-cKDEnKbeHTu7ZnvqpqPQ',
    appId: '1:453272669944:ios:627e617353f775fbc0b50d',
    messagingSenderId: '453272669944',
    projectId: 'schederated',
    storageBucket: 'schederated.appspot.com',
    iosClientId: '453272669944-mjdicguoudlr4e85p1567pstubssktk6.apps.googleusercontent.com',
    iosBundleId: 'com.schederated.flutterSchederated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCky9F4k-1SDV-cKDEnKbeHTu7ZnvqpqPQ',
    appId: '1:453272669944:ios:627e617353f775fbc0b50d',
    messagingSenderId: '453272669944',
    projectId: 'schederated',
    storageBucket: 'schederated.appspot.com',
    iosClientId: '453272669944-mjdicguoudlr4e85p1567pstubssktk6.apps.googleusercontent.com',
    iosBundleId: 'com.schederated.flutterSchederated',
  );
}
